apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-wordPress-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    availabilityZones: ["us-east-1a", "us-east-1b"]
    ssh: #public key
      publicKeyName: eks
